version: '3.9'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment: 
        MYSQL_DATABASE: shortener_db
        MYSQL_USER: sh_admin
        MYSQL_PASSWORD: FYghdgs%!ff3
    volumes:
        - ./storage/dbdata:/var/lib/mysql
    ports:
        - 3308:3308
  main:
    build:
      context: .
      dockerfile: Dockerfile

    links:
      - db
    depends_on:
      - db

    restart: on-failure:50

    command: 'php artisan serve --host=0.0.0.0'
    volumes:
        - .:/app
    ports:
        - 8000:8000